[build]
builder = "nixpacks"
buildCommand = "npm ci"

[deploy]
startCommand = "cd app && node src/index.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
numReplicas = 1