[build]
builder = "nixpacks"
buildCommand = "cd packages/backend && npm ci"

[deploy] 
startCommand = "cd packages/backend && node src/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
numReplicas = 1